

###
GET http://localhost:4000/product-api/product
###
GET http://localhost:4000/product-api/product/1234
###
POST http://localhost:4000/product-api/product
content-Type:application/json

{ 
   "productId":1234,
   "productName":"purse",
   "price":40000,
   "brand":"gucci"

}
###
PUT http://localhost:4000/product-api/product/1234
content-Type:application/json

{
     "productId":1234,
   "productName":"purse",
   "price":30000,
   "brand":"dior"
}

###
DELETE http://localhost:4000/product-api/product/1234
